version: "3.1"

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:secret@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - db

  ws:
    image: andytango/pg_websocket
    ports:
      - "8080:8080"
    environment:
      PG_URL: postgres://postgres:secret@db:5432/postgres
    depends_on:
      - db
